language: python
python: 3.5

sudo: false

cache:
  directories:
    - $HOME/.pip-cache/

env:
  - TOX_ENV=py27-17
  - TOX_ENV=py27-18
  - TOX_ENV=py27-19
  - TOX_ENV=py34-17
  - TOX_ENV=py34-18
  - TOX_ENV=py34-19
  - TOX_ENV=py35-18
  - TOX_ENV=py35-19
  - TOX_ENV=docs
  - TOX_ENV=flake8

install:
  - pip install tox --cache-dir $HOME/.pip-cache

script:
  - tox -e $TOX_ENV
