language: python
python: 2.7
env:
  - TOX_ENV=py27-17
  - TOX_ENV=py27-18
  - TOX_ENV=py34-17
  - TOX_ENV=py34-18
  - TOX_ENV=docs
  - TOX_ENV=flake8
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
