language: python
python: 2.7
env:
  - TOX_ENV=py26-15
  - TOX_ENV=py26-16
  - TOX_ENV=py27-15
  - TOX_ENV=py27-16
  - TOX_ENV=py33-15
  - TOX_ENV=py33-16
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
